#  Factorización LU



La factorización LU consiste en escribir una Matriz $A$ como la multiplicación de una matriz triangular inferior $L$ y una matriz superior $U$. 

$$A=LU$$

El único requisito matemático para que la factorización exista es que $A$ debe ser invertible. 


## Aplicación

Al igual que la eliminación Gaussiana, este método nos permite resolver sistemas de ecuaciones matriciales de la forma 

$$ Ax = b$$

Donde $A$ es una matriz invertible, $x$ es el vector de incógnitas y $b$ es un vector de constantes del mismo tamaño que $x$. Este sistema matricial lineal, es el equivalente a un sistema de ecuaciones lineales.


### Resolviendo $Ax=b$

Conocidas las matrices $L$ y $U$, se tiene que

$$LUx=b$$

Así, podemos descomponer la ecuación original en

$$Ly=b$$

$$Ux=y$$

Que son dos sistemas matriciales con matrices triangulares, los cuáles se pueden resolver de manera directa al despejar y sustituir.

## Cálculo de $L$ y $U$

En esta sección presentaremos la deducción de 2 métodos para encontrar las matrices $L$ y $U$ explícitamente, así como los problemas asociados a cada uno.

### Método Doolittle

El método Doolittle es un método para encontrar las matrices $L$ y $U$, en el cuál se fija la diagonal de $L$ como 1's. De acuerdo a esta propuesta, se tiene lo siguiente 

$$
\left(
\begin{array}\\
a_{11} & a_{12} & ... & a_{1n} \\
a_{21} & a_{22} & ... & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{n1} & a_{n2} & ... & a_{nn}
\end{array}
\right)
=
\left(\begin{array}\\
 1 & 0 & ... & 0 \\
 l_{21} & 1 & ... & 0 \\
 \vdots & \vdots & \ddots & \vdots \\
 l_{n1} & l_{n2} & ... & 1
 \end{array}
\right)
\left(
 \begin{array}\\
 u_{11} & u_{12} & ... & u_{1n}\\
 0 & u_{22} & ... & u_{2n} \\
 \vdots & \vdots & \ddots & \vdots \\
 0 & 0 & ... & u_{nn}
 \end{array}
\right)
$$

Notamos que de inicio, ya contamos con el primer renglón de $L$.

Así, podemos ver que para el primer renglón de $U$, se tiene que 

$$
a_{1j} = l_{11} u_{1j} = u_{1j}
$$

Por lo que tenemos el primer reglón de $U$.

Para el segundo renglón se tiene que en $L$

$$
a_{21} = l_{21}u_{11}\ \Rightarrow\ l_{21} = \frac{a_{21}}{u_{11}}
$$

Teniendo así el segundo renglón de $L$

Y en general, con $2 \leq j$, se tiene 

$$
a_{2j} = l_{21}u_{1j} + u_{2j}\ \Rightarrow \ u_{2j}= a_{2j} - l_{21}U_{1j}
$$


Para el tercer renglón, se tiene en $L$ que

$$
a_{31} = l_{31}u_{11}\ \Rightarrow\ l_{31} = \frac{a_{31}}{u_{11}}\\
a_{32} = l_{31}u_{12} + l_{32}u_{22}\ \Rightarrow\ l_{32}= \frac{1}{u_{22}}\left( a_{32} - l_{31}u_{21} \right)\\
$$

Teniendo así todo el tercer renglón de $L$

Para $U$ se tiene que

$$
a_{3j} = l_{31}u_{1j} + l_{32}u_{2j} + u_{3j}\\
\Rightarrow\ u_{3j} = a_{3j} - l_{31}u_{1j} - l_{32}u_{2j}
$$


Así, en general, podemos obtener nuestros coeficientes de la siguiente manera

$$
\left\{ 
\begin{array}\\
u_{ij} & = & a_{ij} - \sum_{k=1}^{i-1} l_{ik}u_{kj} \\
l_{ij} & = & \frac{1}{u_{jj}}\left( a_{ij} - \sum_{k=1}^{j-1}l_{ik}u_{kj} \right)
\end{array}
\right.
$$

#### Ejemplo a "mano"

Calcular la factorización de la matriz 

$$
A= \begin{pmatrix}
    1 & 2 & -1\\
    0 & -2 & 1 \\
    -1 & 0 & 1
    \end{pmatrix}
$$

El primer renglón es conocido de antemano, $l_{11}=1$ y $u_{1j}=a_{1j}$

$u_{11} = a_{11}= 1$, $u_{12} = a_{12}=2$, $u_{13} = a_{13} = -1$

Estamos yendo de renglón en renglón, por lo que calulamos primero las $l_{ij}$ y después las $u_{ij}$

$l_{21} = \frac{1}{u_{11}} \left(a_{21} \right) = \frac{0}{1}=0$

La diagonal de $L$ es conocida ya que es al inicio una identidad.

$u_{22} = a_{22} - l_{21}u_{12} = -2 - (0)(2) = -2$

$u_{23} = a_{23} - l_{21}u_{13} = 1 - 0(-1) = 1$

Pasamos al tercer renglón comenzando de nuevo por $L$

$l_{31} = \frac{1}{u_{11}} \left(a_{31} \right)= \frac{-1}{1}=-1 $

$L_{32} = \frac{1}{u_{22}} \left(a_{32} - l_{31}u_{12} \right) = \frac{1}{-2} \left( 0 - (-1)(2) \right) = -1 $ 

Pasamos por último a calcular el elemento restante de $U$

$u_{33} = a_{33} - (l_{31}u_{13} + l_{32}u_{23})= 1 - ( (-1)(-1) + (-1)(1) ) = 1$

Así, nuestras matrices $L$ y $U$ son

$$
L= \left( \begin{array}\\
 1 & 0 & 0\\
 0 & 1 & 0\\
-1 & -1 & 1
\end{array} 
\right)
\\
U = \left(
\begin{array}\\
 1 & 2 & -1\\
 0 & -2 & 1\\
 0 & 0 & 1
\end{array}
\right)
$$

In [ ]:
# import se utiliza para agregar una paquetería a el script actual
# cada que se inicia un nuevo script o notebook, debe importarse 
# las librerias necesarias

import numpy as np

In [ ]:
#Asiganr un nombre a una lista

M = ((1,0,-1), (0,1,1))

In [ ]:
#Acceso al primer elemento de la lista

M[0]

(1, 0, -1)

In [ ]:
#Acceso a elementos en una Matriz

M[0][2]

-1

In [ ]:
#Verificación errónea de ser una matriz cuadrada

if len(M[1]) == len(M[0]):
    print("Es cuadrada")
    
else:
    print("No es cuadrada")

Es cuadrada


In [ ]:
#Convertir una lista de listas en un array de Numpy
M=np.array(M)

In [ ]:
# Ahora M aparece con la palabra array antes de la lista y 
# acomodado como Matriz

M

array([[ 1,  0, -1],
       [ 0,  1,  1]])

In [ ]:
#Acceso a los renglones en un array
M[0]

array([ 1,  0, -1])

In [ ]:
#Definir un array directamente desde una lista

N=np.array([[1,1], 
            [1,-1]])

In [ ]:
#acceso a las columnas en un array

N[:,0]

array([1, 1])

In [ ]:
#Mini código para verificar si la matriz es cuadrada

def comp_cuad(matrix):
    if len(matrix[0]) == len(matrix[:,0]):
        return True
    else:
        return False

In [ ]:
if comp_cuad(M):
    print("Es cuadrada")
else:
    print("No es cuadrada")

No es cuadrada


In [ ]:
#Mini código para verificar si la matriz es invertible

def comp_inv(matrix):
    if np.linalg.det(matrix) == 0:
        return False
    else:
        return True

In [ ]:
if comp_inv(N):
    print("Es invertible")
else:
    print("No es invertible")

Es invertible


In [ ]:
#Programa para calcular la suma de la fórmula para los $l_{ij}$

def sum1(index1, index2, matrix1, matrix2):
    if index2==0:
        return 0
    else:
        suma=0
        for k in range(index2):
            suma = suma + matrix1[index1][k]*matrix2[k][index2]
        return suma

In [ ]:
#Programa para calcular la suma de la fórmula para los $u_{ij}$

def sum2(index1, index2, matrix1, matrix2):
    suma=0
    for k in range(index1):
        suma = suma + matrix1[index1][k]*matrix2[k][index2]
    return suma

In [ ]:
##Programa principal de Doolittle

def Doolittle(matrix):
    matrix=np.array(matrix) #Volvemos array la matriz ingresada por si a caso no lo fuera
    if comp_cuad(matrix):
        if comp_inv(matrix):
            
            lower=np.eye(len(matrix[0])) #Comando para crear la matriz identidad
            
            upper=np.zeros((len(matrix[0]),len(matrix[:,0]))) #Comando para crear una matriz de ceros
            
            for j in range(len(matrix[0])): #Llenamos el primer renglón de U
                upper[0][j] = matrix[0][j]
            
            for i in range(1,len(matrix[0])):    #for para recorrer los índices llendo de renglón en renglón
                for j in range(len(matrix[:,0])):  # el índice i es para renglones y el j para columnas
                    if j<i:
                        lower[i][j] = (1/upper[j][j])*(matrix[i][j] - sum1(i,j,lower,upper)) #Cálculo de L con la función suma auxiliar
                    else:
                        upper[i][j] = matrix[i][j] - sum2(i,j,lower, upper) #Cálculo de U con la función suma auxiliar
            
            return (lower,upper) #Regresamos una dupla que tenga la primer entrada a L y la segunda a U
            
        else:
            print("La matriz no es invertible")
    else:
        print("La matriz no es cuadrada")

In [ ]:
# Comprobación con la Matriz hecha a mano

A=np.array([[1,2,-1], 
            [0,-2,1],
            [-1,0,1]])
Doolittle(A)

(array([[ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [-1., -1.,  1.]]), array([[ 1.,  2., -1.],
        [ 0., -2.,  1.],
        [ 0.,  0.,  1.]]))

In [ ]:
##Importación de librería

import random as rand

In [ ]:
# Una comprobación que puede hacerse en general es la siguiente

# Creamos una función que haga matrices aleatorias de dimensión n

# Arriba se importó la librería de random para hacer 
# números pseudo-aleatorios

# Generaremos enteros entre -100 y 100

def rand_matrix_int(n):
    matrix=np.zeros((n,n)) #array de ceros
    for i in range(n):
        for j in range(n):
            matrix[i][j]=rand.randint(-10,10)
    matrix=np.array(matrix)
    return matrix

In [ ]:
#Probamos nuestra función

rand_matrix_int(3)

array([[-1.,  0.,  8.],
       [-8., -3.,  3.],
       [ 0.,  1.,  7.]])

In [ ]:
# Para comprobar nuestro programa le metemos matrices aleatorias
# Multiplicamos L y U y le restamos la original

Rand=((1,2,1),(0,2,-1),(0,-1,2)) #Generación de matriz aleatoria

print("Matriz a factorizar",Rand) #Vista de la matriz
print(" ")
print("L",Doolittle(Rand)[0]) #Matriz L
print(" ")
print("U", Doolittle(Rand)[1]) #Matriz U
print(" ")
print("Resta de la original y la multiplicación",
      np.matmul(Doolittle(Rand)[0],Doolittle(Rand)[1]) - Rand)

Matriz a factorizar ((1, 2, 1), (0, 2, -1), (0, -1, 2))
 
L [[ 1.   0.   0. ]
 [ 0.   1.   0. ]
 [ 0.  -0.5  1. ]]
 
U [[ 1.   2.   1. ]
 [ 0.   2.  -1. ]
 [ 0.   0.   1.5]]
 
Resta de la original y la multiplicación [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Método de Cholesky


El método de Cholesky, es un tipo de Factorización LU, el cuál se puede aplicar para matrices positivo definidas. El resultado de esta factorización, es que  la matriz $U$ será la traspuesta de la $L$, es decir

$$U = L^T \\
A = L L^T$$


Una matriz $M$ positivo definida es aquella que cumple ser simétrica y que 

$$x^T M X > 0$$

Donde $x$ es un vector arbitrario.

Recordemos que una matriz simétrica $M$ cumple que $M_{ij} = M_{ji}$.


Otra forma de verificar que una matriz sea positivo definida es que dados $\lambda_i$ eigenvalores de $M$, se cumple que $\forall i, \lambda_i >0 $.


Dadas las condiciones, pasamos a deducir cómo encontrar explícitamente nuestra matriz $L$.


Con nuestras condiciones, supones que existe $A$ invertible y simétrica, tal que

$$
\left(\begin{array}\\
          a_{11} & a_{12} & ... & a_{n1}\\
          a_{12} & a_{22} & ... & a_{2n}\\
          \vdots & \vdots & \ddots & \vdots \\
          a_{n1} & a_{2n} & ... & a_{nn}
           \end{array}
     \right)
=
\left(\begin{array}\\
        l_{11} & 0 & ... & 0\\
        l_{21} & l_{22} & ... & 0\\
        \vdots & \vdots & \ddots & \vdots \\
        l_{n1} & l_{n2} & ... & l_{nn}
       \end{array}
\right)
\left(\begin{array}\\
   l_{11} & l_{21} & ... & l_{n1}\\
   0 & l_{22} & ... & l_{n2}\\
   \vdots & \vdots & \ddots & \vdots \\
   0 & 0 & ... & l_{nn}
   \end{array}
\right)
$$

Así, podemos ver que 

$a_{11} = l_{11}^2\ \Rightarrow\ l_{11}=\sqrt{a_{11}}$

y en general para $j>1$, se tiene que

$ a_{1j} = l_{11}l_{j1}\ \Rightarrow\ l_{j1} = \frac{a_{1j}}{l_{11}} $

de esta manera, tenemos el primer renglón y columna encontrados.

Pasando al segundo renglón, se tiene que no debemos preocuparnos por $l_{21}$ y comenzamos con $l_{22}$. Notamos que 

$a_{22} = l_{21}^2 + l_{22}^2\ \Rightarrow\ l_{22} = \sqrt{a_{22} - l_{21}^2} $

y en general, para $j>2$, se tiene que

$a_{2j} = l_{21}l_{j1} + l_{22}l_{j2}\ \Rightarrow\ l_{j2} = \frac{1}{l_{22}} (a_{2j} - l_{21}l_{j1}) $

Hacemos el tercer renglón para generalizarlo.

Notamos que los 2 primeros renglones y columnas ya los tenemos, así, basta iniciar desde $j=3$.

$a_{33} = l_{31}^2 + l_{32}^2 + l_{33}^2\ \Rightarrow\ l_{33}=\sqrt{a_{33} - l_{31}^2 - l_{32}^2}$

y en general, para $j>3$ se tiene que:

$a_{3j} = l_{31}l_{j1} + l_{32}l_{j2} + l_{33}l_{j3}\ \Rightarrow\ l_{j3} = \frac{1}{l_{33}}( a_{3j} - l_{31}l_{j1} - l_{32}l_{j2}) $

Podemos generalizar entonces que 

$$
\left\{
\begin{array}\\
l_{ii} & = & \sqrt{ a_{ii} - \sum_{k=1}^{i-1} l_{ik}^2} & i=j \\
l_{ji} & = & \frac{1}{l_{ii}}(a_{ij} - \sum_{k=1}^{i-1} l_{ik}l_{jk}) & i<j
\end{array}
\right.
$$

Ejemplo a mano:

$$
A=\left(
\begin{array}\\
 1 & 0 & -1\\
 0 & 1 & 0\\
 -1 & 0 & 2\\
 \end{array}
 \right)
$$

Comenzamos con la primer columna de $L$

$l_{11} = \sqrt{a_{11}} = 1$
$l_{21} = \frac{1}{l_{11}}(a_{12}) = 0$
$l_{31} = \frac{1}{l_{11}}(a_{13}) = -1$

Ahora, pasamos a la segunda columna de $L$.

$l_{22} = \sqrt{a_{22} - l_{21}^2} = \sqrt{1 - 0} = 1$
$l_{32} = \frac{1}{l_{22}}(a_{23} - l_{21}l_{31}) = (0 - 0)=0$

Por último, cálculamos $l_{33}$

$l_{33} = \sqrt{a_{33} - l_{31}^2 - l_{32}^2} = \sqrt{2 - (-1)^2 - 0^2}=1


Así, tenemos que:

$$
A=\left(
\begin{array}\\
 1 & 0 & -1\\
 0 & 1 & 0\\
 -1 & 0 & 2\\
 \end{array}
 \right)
 =
 \left(
\begin{array}\\
 1 & 0 & 0\\
 0 & 1 & 0\\
 -1 & 0 & 1\\
 \end{array}
 \right)
  \left(
\begin{array}\\
 1 & 0 & -1\\
 0 & 1 & 0\\
 0 & 0 & 1\\
 \end{array}
 \right)
$$

In [ ]:
#Código de comprobación de simetría
def comp_symme(matrix):
    for i in range(len(matrix[0])):
        for j in range(i,len(matrix[:,0])):
            if matrix[i][j]==matrix[j][i]:
                value=True
            else:
                return False
    return value

In [ ]:
#Prueba del código de comprobación

sym1=np.array([[1,2,3],
               [2,4,5],
               [3,5,6]])
if comp_symme(sym1):
    print("Es simétrica")
else:
    print("No es simétrica")

Es simétrica


In [ ]:
#código de comprobación de definido-positiva

def comp_posit_def(matrix):
    for i in range(len(np.linalg.eig(matrix)[0])):
        if np.linalg.eig(matrix)[0][i]>0:
            value=True
        else:
            return False
    return value

In [ ]:
#Prueba de la comprobación de positivos definidos
diag1=np.diag((1,2,1))

if comp_posit_def(diag1):
    print("Es positivo definida")
else:
    print("No es positivo definida")

Es positivo definida


In [ ]:
## codigo auxiliar de suma

def suma_cho_1(index, matrix):
    if index==0:
        return 0
    else:
        suma=0
        for k in range(index):
            suma += matrix[index][k]**2
        return suma

In [ ]:
#Código auxiliar de suma 2

def suma_cho_2(index1, index2, matrix):
    if index2==0:
        return 0
    else:
        suma=0
        for k in range(index1):
            suma += matrix[index1][k]*matrix[index2][k]
        return suma

In [ ]:
#Librería necesaria para sacar raíces cuadradas

import math

In [ ]:
def Cholesky(matrix):
    matrix = np.array(matrix)
    if comp_cuad(matrix):
        if comp_inv(matrix):
            if comp_symme(matrix):
                if comp_posit_def(matrix):
    
    
                    lower=np.zeros((len(matrix[0]),len(matrix[:,0])))

                    for i in range(len(matrix[0])):
                        for j in range(i,len(matrix[0])):
                            if i==j:
                                lower[i][i] = math.sqrt(matrix[i][i] - suma_cho_1(i,lower))
                            else:
                                lower[j][i] = (1/lower[i][i])*(matrix[i][j] - suma_cho_2(i,j,lower))
                    return lower
                else:
                    print("No es positivo-definida")
            else:
                print("No es una matriz simétrica")
        else:
            print("No tiene inversa")
    else:
        print("No es una matriz cuadrada")

In [ ]:
Cholesky(np.array([[1,0,-1],[0,1,0],[-1,0,2]]))

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [-1.,  0.,  1.]])

In [ ]:
def randint_sym_mat(n):
    matrix=np.zeros((n,n))
    for i in range(n):
        for j in range(i,n):
            matrix[i][j]=rand.randint(0,10)
            matrix[j][i]=matrix[i][j]
    return matrix

In [ ]:
randint_sym_mat(3)

array([[8., 9., 7.],
       [9., 8., 1.],
       [7., 1., 1.]])

In [ ]:
proof=randint_sym_mat(3)

print("A=", proof)
print(" ")
L=Cholesky(proof)
print("L=",L)
print(" ")
print("A-LL^T=",proof - np.matmul(L,L.transpose()))

A= [[1. 1. 8.]
 [1. 5. 3.]
 [8. 3. 8.]]
 
No es positivo-definida
L= None
 


AttributeError: ignored